### ISSUE TITLE
When seq is high, errors with permission denied

### ISSUE THREAD

**Issue by bernardotorres** [gteissier/srtp-decrypt#1]
Uses a int16 to get the diff. When seq is high, it gives a wrong diff.
diff should be uint16_t

**Comment by adeellhr786** [comment]
hi there ,i have tried setting tag length 10/0 both doesnt works it says , purmission  denied 
basically what i am doing is : 
i capture packets of Skype For business(known as lync lately ) then i decode them via your code , i know skype for business call uses Silk encoder, so i can decode packets from SRTP and then use Silk to decode packets this is what i  am getting in SDP
 
a=ice-pwd:MwkJYGtSbYUjvFgQSJVI1oLd
a=candidate:1 1 UDP 2130706431 192.168.1.30 50464 typ host
a=candidate:1 2 UDP 2130705918 192.168.1.30 50465 typ host
a=candidate:2 1 tcp-act 1684798975 192.168.1.30 50464 typ srflx raddr 192.168.1.30 rport 50464
a=candidate:2 2 tcp-act 1684798462 192.168.1.30 50464 typ srflx raddr 192.168.1.30 rport 50464
a=label:main-audio
a=crypto:2 AES_CM_128_HMAC_SHA1_80 inline:XZhQhew2K31w0uYdMe2i3zcT7QDEuPrG8QdM1kJq|2^31|1:1
Please Help

**Comment by gteissier** [comment]
Hi there

 

By chance, is it possible that you send me:

- SRTP packets, in the form of a pcap

- full SDP offer and answer


 

Regards,

Guillaume


Sent: Tuesday, February 28, 2017 at 6:35 AM

**Comment by adeellhr786** [comment]
first of all many thanks for the response 
i have uploaded pcap and SDP in a text file , zipped them both and uploaded both in dropbox here
https://www.dropbox.com/s/ve7ecg91vb4l82d/zeeshan.zip?dl=0
cant wait for your response its been weeks since i am trying to tackle this problem

**Comment by gteissier** [comment]
First of all, sorry for the late answer.

The encrypted traffic embeds MKI, which appears as four bytes, in big-endian order, between the encrypted payload and the authentication tag.

As a consequence, trafic can not be authenticated, as MKI is inserted after computing authentication tag. You should be able to successfully decrypt the ciphered packets by first removing MKI from frames, then decrypt the mangled frames using srtp-decrypt.
